# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

start_profiler <- function(str = "RcppProfiler.log") {
    .Call('RcppProfiler_start_profiler', PACKAGE = 'RcppProfiler', str)
}

stop_profiler <- function() {
    .Call('RcppProfiler_stop_profiler', PACKAGE = 'RcppProfiler')
}

